# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ab5d2fd17f50da89bab216fbf8bcf6620fb5a186e4b4bc96cb9575440547f169674d3385b96f60b5ec92a4009f2e3ce2919983ff221bb8df0febd6b5c2ed760

test:
  secret_key_base: adf2dc9b8fa9ab3f8fe148bd80759e3d4585011c07438643d6786b56dc06ccb4965c76dd5bed9823050b0047dcb2965f1020da7a2dbc568324db21f1f6660141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
